# Generated by Django 4.2.4 on 2023-08-25 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_alter_airport_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["-departure_time", "route"]},
        ),
    ]
